# 应用服务 WEB 访问端口
server:
  port: 8080
  servlet:
    session:
      timeout: 2000
    context-path: /invoice
    encoding:
      enabled: true
      charset: UTF-8
      force: true
  tomcat:
    connection-timeout: 10000
    uri-encoding: UTF-8

# 应用名称
spring:
  application:
    name: Invoice
  # THYMELEAF (ThymeleafAutoConfiguration)
  thymeleaf:
    # 开启模板缓存（默认值： true ）
    cache: false
    # 模板编码
    encoding: UTF-8
    # 开启 MVC Thymeleaf 视图解析（默认值： true ）
    enabled: true
    # 要运⽤于模板之上的模板模式。另⻅ StandardTemplate-ModeHandlers( 默认值： HTML5)
    mode: HTML5

